#!/bin/bash
set -e

MYSQL_PASSWORD=Seguridad101

mysql -u root << EOF
CREATE DATABASE keystone;
GRANT ALL ON keystone.* TO 'keystone'@'%' IDENTIFIED BY '$MYSQL_PASSWORD';
GRANT ALL ON keystone.* TO 'keystone'@'localhost' IDENTIFIED BY '$MYSQL_PASSWORD';
GRANT ALL ON keystone.* TO 'keystone'@'$HOST_IP' IDENTIFIED BY '$MYSQL_PASSWORD';
FLUSH PRIVILEGES;

CREATE DATABASE glance CHARSET=utf8;
GRANT ALL ON glance.* TO 'glance'@'%' IDENTIFIED BY '$MYSQL_PASSWORD';
GRANT ALL ON glance.* TO 'glance'@'localhost' IDENTIFIED BY '$MYSQL_PASSWORD';
GRANT ALL ON glance.* TO 'glance'@'$HOST_IP' IDENTIFIED BY '$MYSQL_PASSWORD';
FLUSH PRIVILEGES;

CREATE DATABASE nova;
GRANT ALL ON nova.* TO 'nova'@'%' IDENTIFIED BY '$MYSQL_PASSWORD';
GRANT ALL ON nova.* TO 'nova'@'localhost' IDENTIFIED BY '$MYSQL_PASSWORD';
GRANT ALL ON nova.* TO 'nova'@'$HOST_IP' IDENTIFIED BY '$MYSQL_PASSWORD';
FLUSH PRIVILEGES;

CREATE DATABASE cinder;
GRANT ALL ON cinder.* TO 'cinder'@'%' IDENTIFIED BY '$MYSQL_PASSWORD';
GRANT ALL ON cinder.* TO 'cinder'@'localhost' IDENTIFIED BY '$MYSQL_PASSWORD';
GRANT ALL ON cinder.* TO 'cinder'@'$HOST_IP' IDENTIFIED BY '$MYSQL_PASSWORD';
FLUSH PRIVILEGES;
EOF