#!/bin/bash
#
# This is mostly based on https://github.com/fornyx/OpenStack-Havana-Install-Guide/blob/master/OpenStack-Havana-Install-Guide.rst
#
# Tweaked a bit to work inside LXC.
#
# Needs module scsi_transport_iscsi and nbd loaded in the host
#
set -e
[ -n "$DEBUG" ] && set -x

LSTACK_VERSION=0.90
INSTALL_DIR=/usr/share/lstack
BASE_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
if ! [ -f "$BASE_PATH/lib/lstack.sh" ]; then
  # lib goes here when installing from a package
  BASE_PATH=$INSTALL_DIR
fi
source $BASE_PATH/lib/dispatch.sh

main() {
  export LC_ALL=en_US.UTF-8
  if [ -z "$SUDO_USER" ]; then
    export LSTACK_NAME=lstack-`whoami`
  else
    export LSTACK_NAME=lstack-$SUDO_USER
  fi
  export LSTACK_ROOTFS="/var/lib/lxc/$LSTACK_NAME/rootfs"
  export LSTACK_CONF_DIR="$HOME/.config/lstack"
  export LSTACK_LOGFILE="/tmp/$LSTACK_NAME.log"

  source $BASE_PATH/lib/lstack.sh
  need_pkg "sudo"
  need_pkg "lxc"
  need_pkg "iscsitarget-dkms"


  dispatch lstack "$@"
}

lstack_command_bootstrap()     ( source $BASE_PATH/lib/commands/bootstrap.sh )
lstack_command_destroy()       ( source $BASE_PATH/lib/commands/destroy.sh )
lstack_command_nova()          ( source $BASE_PATH/lib/commands/nova.sh )
lstack_command_ssh()           ( source $BASE_PATH/lib/commands/ssh.sh )
lstack_command_help()          ( source $BASE_PATH/lib/commands/help.sh )
lstack_command_info()          ( source $BASE_PATH/lib/commands/info.sh )
lstack_command_ip()            ( source $BASE_PATH/lib/commands/ip.sh)
lstack_command_importimg()     ( source $BASE_PATH/lib/commands/importimg.sh )
lstack_command_deploy()        ( source $BASE_PATH/lib/commands/deploy.sh )
lstack_command_forward()       ( source $BASE_PATH/lib/commands/forward.sh )

lstack_option_help()    ( source $BASE_PATH/lib/commands/help.sh )
lstack_option_version() ( echo lstack v$LSTACK_VERSION )
lstack_option_nocolor() ( export LSTACK_NOCOLOR=1; dispatch lstack "$@" )
lstack_option_quiet()   ( export LSTACK_QUIET=1; dispatch lstack "$@" )
lstack_ ()              ( source $BASE_PATH/lib/commands/help.sh )

main $@
