#!/bin/bash
#
# This is mostly based on https://github.com/fornyx/OpenStack-Havana-Install-Guide/blob/master/OpenStack-Havana-Install-Guide.rst
#
# Tweaked a bit to work inside LXC.
#
# Needs module scsi_transport_iscsi and nbd loaded in the host
#
set -e
[ -n "$DEBUG" ] && set -x

INSTALL_DIR=/usr/share/oslxc
BASE_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
if ! [ -f "$BASE_PATH/oslxc/lib.sh" ]; then
  # lib goes here when installing from a package
  BASE_PATH=$INSTALL_DIR
fi
source $BASE_PATH/oslxc/dispatch.sh

oslxc_command_bootstrap() ( source $BASE_PATH/oslxc/commands/bootstrap.sh )
oslxc_command_destroy() ( source $BASE_PATH/oslxc/commands/destroy.sh )
oslxc_command_nova() ( source $BASE_PATH/oslxc/commands/nova.sh )
oslxc_command_ssh() ( source $BASE_PATH/oslxc/commands/ssh.sh )
oslxc_command_help () ( source $BASE_PATH/oslxc/commands/help.sh )

oslxc_option_help() ( echo "Usage: oslxc [options] [command]" )
oslxc_option_version() ( echo oslxc v0.1 )
oslxc_ () ( source $BASE_PATH/oslxc/commands/help.sh )

dispatch oslxc "$@"
