#!/bin/bash
set -e

BASE_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )/../" && pwd )"

lstack() {
  $BASE_PATH/lstack $@
}

cleanup() {
  lstack destroy >/dev/null 2>&1 || true
}
trap "cleanup" EXIT

lstack bootstrap

# Wait for the instance to boot
for i in $(seq 1 10); do
  cirros_ip=$(lstack nova list |grep -o "private=.*\s"|cut -d= -f2|tr -d ' ') \
    || true
  [ -n "$cirros_ip" ] && break

  sleep 5
done

if [ -z "$cirros_ip" ]; then
  >&2 echo Cirros instance IP not found.
  exit 1
fi


# A test Cirros VM is created by default when bootstrapping
# The SSH port should be reachable if everything went fine.
echo "Testing Cirros instance SSH ($cirros_ip)..."
# SSH daemon may take some time to come up, so we need to wait.
for i in $(seq 1 10); do
  (lstack ssh "echo | nc $cirros_ip 22" | grep dropbear > /dev/null) && {
    ssh_ok=1
    break
  }

  sleep 5
done
if [ -z "$ssh_ok" ]; then
  >&2 echo Cirros instance SSH test failed!
  exit 1
fi

# Test 22 port forward
ssh_ok=""
lstack forward test 22
echo | nc $(lstack ip) 22 | grep dropbear > /dev/null && ssh_ok=1
if [ -z "$ssh_ok" ]; then
  >&2 echo "SSH forward test (instance) failed!"
  exit 1
fi

ssh_ok=""
echo | nc $(lstack ip) 2200 | grep OpenSSH > /dev/null && ssh_ok=1
if [ -z "$ssh_ok" ]; then
  >&2 echo "SSH forward test (container) failed!"
  exit 1
fi

echo OK!
